### ISSUE TITLE
Server error Pop up

### ISSUE THREAD

**Issue by Nikhil-Jorge** [frappe/changemakers#136]
### App Versions
```
{
	"changemakers": "1.0.0",
	"frappe": "15.0.0-dev"
}
```
### Route
```
Workspaces/Changemakers
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 847, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/reportview.py", line 22, in get
    args = get_form_params()
  File "apps/frappe/frappe/desk/reportview.py", line 71, in get_form_params
    validate_args(data)
  File "apps/frappe/frappe/desk/reportview.py", line 76, in validate_args
    parse_json(data)
  File "apps/frappe/frappe/desk/reportview.py", line 219, in parse_json
    data["filters"] = json.loads(data["filters"])
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Shelter Home",
		"fields": "[\"name\",\"modified\"]",
		"filters": null,
		"order_by": "modified desc",
		"start": 0,
		"page_length": 4
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.reportview.get",
	"request_id": "1f8db11c-046d-4e4e-890e-6f85131c7722"
}
```
### Response Data
```
{
	"exception": "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)",
	"exc_type": "JSONDecodeError"
}
```

**Comment by NagariaHussain** [comment]
Workspace issue, fixed during call today.
